### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by G-Sudarshan**

### CODE REVIEW

**Review by Manoj-Paramsetti — CHANGES_REQUESTED** [review]
#### Hello @G-Sudarshan
I guess, you're using MX-Linux. 
If so?
Add the neofetch in image format. Upload that image to `imgur` and use that image link to display the image in the README.md file

**Comment by G-Sudarshan** [comment]
Yes, I'll add

**Comment by G-Sudarshan** [comment]
I have created

**Review by KamalDGRT — APPROVED** [review]
Thank you for your contribution @G-Sudarshan ✨

**Review by Manoj-Paramsetti — APPROVED** [review]

**Pull request merged**
